export const RESPONSE_MESSAGE = {
  USER_CREATED: "User created successfully.",
  USER_UPDATED: "User updated successfully.",
  USER_DELETED: "User deleted successfully.",
  USER_FETCHED: "User fetched successfully.",
  USERS_FETCHED: "Users fetched successfully.",
  INVALID_CREDENTIALS: "Invalid email or password.",
  UNAUTHORIZED: "Unauthorized.",
  FORBIDDEN: "Forbidden.",
  USER_NOT_FOUND: "User not found.",
  USER_DISABLED: "User is disabled.",
  EMAIL_ALREADY_EXISTS: "Email already exists.",
  USERNAME_ALREADY_EXISTS: "Username already exists.",
  VALIDATION_FAILED: "Validation failed.",
  INTERNAL_SERVER_ERROR: "Something went wrong.",
  INVALID_ROLE: "Invalid role.",
  INVALID_REFRESH_TOKEN: "Invalid refresh token.",
  REFRESH_TOKEN_EXPIRED: "Refresh token has expired.",
  LOGOUT_SUCCESS: "Logout successful.",
  LOGIN_SUCCESS: "Login successful.",
  TOKEN_REFRESHED: "Token refreshed successfully.",
  INVALID_ACCESS_TOKEN: "Invalid access token.",
} as const;